name: Build

on:
  push:
    branches: [ minSdk16 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v7
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        cache-provider: 'basic'
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk

    - name: Update tag
      run: |
        git tag -f api16
        git push -f origin tag api16

    - name: Delete release
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release delete api16 -y

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create api16 --title "Android 4 release" --notes "This release is for devices running Android 4.1 to 4.4" --latest=false 'app/build/outputs/apk/release/*.apk'
